stop with exitcode 0 after successful unregistering

diff --git a/entrypoint b/entrypoint
--- a/entrypoint
+++ b/entrypoint
@@ -44,6 +44,7 @@ if [ -n "$TZ" ]; then
 fi
 
 unregister_all_runners() {
+  echo "Unregister and stop all runners..."
   if [ -f /etc/gitlab-runner/config.toml ]; then
     for n in `cat /etc/gitlab-runner/config.toml | grep -Eo 'name = "(.*)"' | cut -d= -f2 | cut -d\" -f2`; do
       echo "Unregister runner $n..."
@@ -53,9 +54,18 @@ unregister_all_runners() {
 }
 
 _term() {
-  echo "Stopped runner"
   unregister_all_runners
-  kill -TERM "$child"
+  unregister_exit_code="$?"
+
+  # terminate `gitlab-runner run` command
+  kill -TERM "$gitlab_runner_pid"
+
+  if [ "$unregister_exit_code" -ne "0" ]; then
+    echo "Unregister failed"
+    exit $unregister_exit_code
+  else
+    exit 0
+  fi
 }
 
 trap _term TERM INT QUIT
@@ -77,7 +87,7 @@ gitlab-runner register \
     --locked=${LOCKED:-false} \
     $ADDITIONAL_OPTIONS
 
-# exit if gitlab-runner command returned exit code != 0
+# exit if `gitlab-runner register` returned exit code != 0
 if [ "$?" -ne "0" ]; then
   exit "$?"
 fi
@@ -89,6 +99,5 @@ printf $NC
 
 echo "Running runner..."
 gitlab-runner run &
-
-child=$!
-wait "$child"
+gitlab_runner_pid=$!
+wait "$gitlab_runner_pid"
